Update android-release.yml

diff --git a/.github/workflows/android-release.yml b/.github/workflows/android-release.yml
--- a/.github/workflows/android-release.yml
+++ b/.github/workflows/android-release.yml
@@ -23,8 +23,13 @@ jobs:
 
       - name: Decode keystore
         run: |
-          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > $GITHUB_WORKSPACE/kate.jks
-  
+          echo "${{ secrets.SIGNING_KEY }}" | tr -d ' \n\r' | base64 -d > $GITHUB_WORKSPACE/kate.jks
+          echo "Keystore size: $(wc -c < $GITHUB_WORKSPACE/kate.jks) bytes"
+          keytool -list -keystore $GITHUB_WORKSPACE/kate.jks \
+            -storepass ${{ secrets.KEY_STORE_PASSWORD }} \
+            -storetype JKS \
+            -noprompt && echo "Keystore valid!" || echo "Keystore INVALID!"
+            
       - name: Grant execute permission
         run: chmod +x gradlew
 
